# Generated by Django 5.1.7 on 2025-03-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_alter_shorturl_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickanalytics',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
