# Generated by Django 5.1.7 on 2025-03-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_clickanalytics_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='browser',
            new_name='browser_info',
        ),
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='device',
            new_name='device_info',
        ),
    ]
