# Generated by Django 5.1.1 on 2025-05-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_rename_browser_clickanalytics_browser_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='browser_info',
            new_name='browser',
        ),
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='device_info',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='location_city',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='clickanalytics',
            old_name='clicked_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='clickanalytics',
            name='location_country',
        ),
    ]
